### ISSUE TITLE
请问麻雀算法怎么用于超参数寻优？

### ISSUE THREAD

**Issue by PinkneyWu** [LucXiong/Swarm-intelligence-optimization-algorithm#1]

**Comment by PinkneyWu** [comment]
可以同时优化连续变量和离散变量吗，比如batch_size和learning_rate

**Comment by LucXiong** [comment]
个人认为不太能直接同时优化连续变量和离散变量，不过可以考虑用连续变量来表示离散变量。比如设定batch_size_pre为连续变量，通过取整取模的方式映射到batch_size，对优化得到的batch_size_pre进行同样的处理即可得到优化后的batch_size

**Comment by PinkneyWu** [comment]
请问下笔者，我看论文写的是先找出最佳和最差个体[](
![image](https://user-images.githubusercontent.com/98322289/176894720-16a5ce9d-7428-470f-ad51-8d1838c5911a.png))，你的代码这里先更新发现者位置在找最差值[](
![image](https://user-images.githubusercontent.com/98322289/176895133-73ab1da3-7f92-4d26-ba8e-234a89c502de.png)
)这两者会有区别吗？

**Comment by PinkneyWu** [comment]
请问下笔者，我看论文写的是先找出最佳和最差个体，你的代码这里先更新发现者位置在找最差值，这两者会有区别吗？
![image](https://user-images.githubusercontent.com/98322289/176895631-109e32f6-ca09-42a9-be9d-feff2ebb2eee.png)
![image](https://user-images.githubusercontent.com/98322289/176895679-0f8d4fc4-e029-44f7-ae7a-7dc8cc872f0d.png)

**Comment by LucXiong** [comment]
在第一次迭代开始之前，初始化中已找过最好和最差值；在非第一次迭代中，其上一次迭代结束时，也寻找了最好和最差值；所以效果和原论文中应该是一样的。
